### PR TITLE
Download list of patches in file.

### PR DESCRIPTION
**Pull request by pau1ie**
Hi Lucas

I have to maintain a number of applications which don't have recommended patches, so I thought it would be nice to have a utility that downloads a list of patches for particular platforms. I thought I would use your downloader as a basis for this, so have added that functionality. I also made the following changes to your existing functionality:

- Check if the enterprise manager files are newer than 24 hour old and if so, don't redownload them.
- Calculate the size of the EM files rather than guessing 300m
- Allow username and password to be supplied on the command line
- Allow password to be prompted.

Apart from caching of the EM files, I believe I haven't altered the functionality of the existing options.
Are you interested in pull requests?
If so, do you have time to review what I have done, and do you have any concerns that you would like me to address?

Thanks

PaulH

### CODE REVIEW

**Comment by lucaslellis** [comment]
Hi Paul,

I'm definitely interested in receiving PRs.

Thanks for your contributions, I'll review them as soon as possible and merge them to main branch if everything's fine.

**Comment by lucaslellis** [comment]
Hi @pau1ie,

I merged your PR into the develop branch, added a few fixes (mostly formatting issues) and also added an option to forcefully refresh the em_catalog.zip.

I've recently had an SR opened with Oracle as the 2022 July catalog did not contain all the recommended patches, so having a new catalog is useful in these debug situations.

I'll perform some tests during the week and merge the changes to the main branch if no further issues are found.

**Comment by pau1ie** [comment]
Great! Thanks!

**Comment by lucaslellis** [comment]
Approved and merged to the develop branch.

**Pull request closed without merging**
